version: 2.1

orbs:
  architect: giantswarm/architect@5.1.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          context: architect
          binary: capi-node-labeler-app
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-capi-node-labeler-app-to-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "capi-node-labeler"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
