apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
  {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
  {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
    {{- include "labels.selector" . | nindent 8 }}
    spec:
      containers:
        - name: "node-labeler"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccountName: {{ include "resource.default.name" . }}
      terminationGracePeriodSeconds: 0
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
